FROM node:8-alpine

RUN apk update && apk add openssh-client make git
RUN npm install --global yarn

ADD ssh /root/.ssh
RUN ssh-keyscan -t rsa hyperion.etnur.net >> /root/.ssh/known_hosts && chown -R root.root /root/.ssh && chmod 600 /root/.ssh/*
ADD etc /etc

VOLUME ["/project"]

WORKDIR /project

CMD ["/bin/ash"]
